package types

import (
	"github.com/cosmos/cosmos-sdk/codec/types"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/cosmos/cosmos-sdk/types/msgservice"
)

// RegisterInterfaces registers the concrete proto types and interfaces with the SDK interface registry
func RegisterInterfaces(registry types.InterfaceRegistry) {
	registry.RegisterImplementations(
		(*sdk.Msg)(nil),
		&MsgCreateWill{},
	)
	// registry.RegisterMsgServiceDesc(registry, _Msg_serviceDesc) // _Msg_serviceDesc is generated by proto-gen
	msgservice.RegisterMsgServiceDesc(registry, &_Msg_serviceDesc)

}
