// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmwasm/will/types.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ExecutionComponent defines a single actionable component within a will.
type ExecutionComponent struct {
	// component_type enables the inclusion of different types of execution
	// component name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// component id
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// components within a will.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// component type
	//
	// Types that are valid to be assigned to ComponentType:
	//	*ExecutionComponent_Transfer
	//	*ExecutionComponent_Claim
	ComponentType isExecutionComponent_ComponentType `protobuf_oneof:"component_type"`
}

func (m *ExecutionComponent) Reset()         { *m = ExecutionComponent{} }
func (m *ExecutionComponent) String() string { return proto.CompactTextString(m) }
func (*ExecutionComponent) ProtoMessage()    {}
func (*ExecutionComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{0}
}

func (m *ExecutionComponent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *ExecutionComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionComponent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *ExecutionComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionComponent.Merge(m, src)
}

func (m *ExecutionComponent) XXX_Size() int {
	return m.Size()
}

func (m *ExecutionComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionComponent.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionComponent proto.InternalMessageInfo

type isExecutionComponent_ComponentType interface {
	isExecutionComponent_ComponentType()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type ExecutionComponent_Transfer struct {
	Transfer *TransferComponent `protobuf:"bytes,4,opt,name=transfer,proto3,oneof" json:"transfer,omitempty"`
}
type ExecutionComponent_Claim struct {
	Claim *ClaimComponent `protobuf:"bytes,5,opt,name=claim,proto3,oneof" json:"claim,omitempty"`
}

func (*ExecutionComponent_Transfer) isExecutionComponent_ComponentType() {}
func (*ExecutionComponent_Claim) isExecutionComponent_ComponentType()    {}

func (m *ExecutionComponent) GetComponentType() isExecutionComponent_ComponentType {
	if m != nil {
		return m.ComponentType
	}
	return nil
}

func (m *ExecutionComponent) GetTransfer() *TransferComponent {
	if x, ok := m.GetComponentType().(*ExecutionComponent_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (m *ExecutionComponent) GetClaim() *ClaimComponent {
	if x, ok := m.GetComponentType().(*ExecutionComponent_Claim); ok {
		return x.Claim
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecutionComponent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecutionComponent_Transfer)(nil),
		(*ExecutionComponent_Claim)(nil),
	}
}

// TransferComponent is used for direct asset transfers.
type TransferComponent struct {
	To     string      `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount *types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *TransferComponent) Reset()         { *m = TransferComponent{} }
func (m *TransferComponent) String() string { return proto.CompactTextString(m) }
func (*TransferComponent) ProtoMessage()    {}
func (*TransferComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{1}
}

func (m *TransferComponent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *TransferComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransferComponent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *TransferComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferComponent.Merge(m, src)
}

func (m *TransferComponent) XXX_Size() int {
	return m.Size()
}

func (m *TransferComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferComponent.DiscardUnknown(m)
}

var xxx_messageInfo_TransferComponent proto.InternalMessageInfo

// ClaimComponent is designed for actions requiring a claim with proof.
type ClaimComponent struct {
	// scheme_type allows for different cryptographic schemes for claims.
	//
	// Types that are valid to be assigned to SchemeType:
	//	*ClaimComponent_Pedersen
	//	*ClaimComponent_Schnorr
	//	*ClaimComponent_Gnark
	SchemeType isClaimComponent_SchemeType `protobuf_oneof:"scheme_type"`
}

func (m *ClaimComponent) Reset()         { *m = ClaimComponent{} }
func (m *ClaimComponent) String() string { return proto.CompactTextString(m) }
func (*ClaimComponent) ProtoMessage()    {}
func (*ClaimComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{2}
}

func (m *ClaimComponent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *ClaimComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClaimComponent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *ClaimComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimComponent.Merge(m, src)
}

func (m *ClaimComponent) XXX_Size() int {
	return m.Size()
}

func (m *ClaimComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimComponent.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimComponent proto.InternalMessageInfo

type isClaimComponent_SchemeType interface {
	isClaimComponent_SchemeType()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type ClaimComponent_Pedersen struct {
	Pedersen *PedersenCommitment `protobuf:"bytes,2,opt,name=pedersen,proto3,oneof" json:"pedersen,omitempty"`
}
type ClaimComponent_Schnorr struct {
	Schnorr *SchnorrSignature `protobuf:"bytes,3,opt,name=schnorr,proto3,oneof" json:"schnorr,omitempty"`
}
type ClaimComponent_Gnark struct {
	Gnark *GnarkZkSnark `protobuf:"bytes,4,opt,name=gnark,proto3,oneof" json:"gnark,omitempty"`
}

func (*ClaimComponent_Pedersen) isClaimComponent_SchemeType() {}
func (*ClaimComponent_Schnorr) isClaimComponent_SchemeType()  {}
func (*ClaimComponent_Gnark) isClaimComponent_SchemeType()    {}

func (m *ClaimComponent) GetSchemeType() isClaimComponent_SchemeType {
	if m != nil {
		return m.SchemeType
	}
	return nil
}

func (m *ClaimComponent) GetPedersen() *PedersenCommitment {
	if x, ok := m.GetSchemeType().(*ClaimComponent_Pedersen); ok {
		return x.Pedersen
	}
	return nil
}

func (m *ClaimComponent) GetSchnorr() *SchnorrSignature {
	if x, ok := m.GetSchemeType().(*ClaimComponent_Schnorr); ok {
		return x.Schnorr
	}
	return nil
}

func (m *ClaimComponent) GetGnark() *GnarkZkSnark {
	if x, ok := m.GetSchemeType().(*ClaimComponent_Gnark); ok {
		return x.Gnark
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClaimComponent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClaimComponent_Pedersen)(nil),
		(*ClaimComponent_Schnorr)(nil),
		(*ClaimComponent_Gnark)(nil),
	}
}

// SchnorrSignature is used for claims that require a Schnorr signature.
type SchnorrSignature struct {
	PublicKey       []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	UniqueSessionId []byte `protobuf:"bytes,2,opt,name=unique_session_id,json=uniqueSessionId,proto3" json:"unique_session_id,omitempty"`
	Signature       []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Message         string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *SchnorrSignature) Reset()         { *m = SchnorrSignature{} }
func (m *SchnorrSignature) String() string { return proto.CompactTextString(m) }
func (*SchnorrSignature) ProtoMessage()    {}
func (*SchnorrSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{3}
}

func (m *SchnorrSignature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *SchnorrSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SchnorrSignature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *SchnorrSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchnorrSignature.Merge(m, src)
}

func (m *SchnorrSignature) XXX_Size() int {
	return m.Size()
}

func (m *SchnorrSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_SchnorrSignature.DiscardUnknown(m)
}

var xxx_messageInfo_SchnorrSignature proto.InternalMessageInfo

// PedersenCommitment enables the use of a Pedersen commitment for claims.
type PedersenCommitment struct {
	Commitment   []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	RandomFactor []byte `protobuf:"bytes,2,opt,name=random_factor,json=randomFactor,proto3" json:"random_factor,omitempty"`
	// enhancing privacy.
	Value          []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	BlindingFactor []byte `protobuf:"bytes,4,opt,name=blinding_factor,json=blindingFactor,proto3" json:"blinding_factor,omitempty"`
}

func (m *PedersenCommitment) Reset()         { *m = PedersenCommitment{} }
func (m *PedersenCommitment) String() string { return proto.CompactTextString(m) }
func (*PedersenCommitment) ProtoMessage()    {}
func (*PedersenCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{4}
}

func (m *PedersenCommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *PedersenCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PedersenCommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *PedersenCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PedersenCommitment.Merge(m, src)
}

func (m *PedersenCommitment) XXX_Size() int {
	return m.Size()
}

func (m *PedersenCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_PedersenCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_PedersenCommitment proto.InternalMessageInfo

// GnarkZkSnark is for claims using zero-knowledge succinct non-interactive
// arguments of knowledge.
type GnarkZkSnark struct {
	VerificationKey []byte `protobuf:"bytes,1,opt,name=verification_key,json=verificationKey,proto3" json:"verification_key,omitempty"`
	PublicInputs    []byte `protobuf:"bytes,2,opt,name=public_inputs,json=publicInputs,proto3" json:"public_inputs,omitempty"`
	Proof           []byte `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *GnarkZkSnark) Reset()         { *m = GnarkZkSnark{} }
func (m *GnarkZkSnark) String() string { return proto.CompactTextString(m) }
func (*GnarkZkSnark) ProtoMessage()    {}
func (*GnarkZkSnark) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{5}
}

func (m *GnarkZkSnark) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *GnarkZkSnark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GnarkZkSnark.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *GnarkZkSnark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GnarkZkSnark.Merge(m, src)
}

func (m *GnarkZkSnark) XXX_Size() int {
	return m.Size()
}

func (m *GnarkZkSnark) XXX_DiscardUnknown() {
	xxx_messageInfo_GnarkZkSnark.DiscardUnknown(m)
}

var xxx_messageInfo_GnarkZkSnark proto.InternalMessageInfo

// Will represents the entire structure of a will.
type Will struct {
	ID          string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator     string                `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Name        string                `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Beneficiary string                `protobuf:"bytes,4,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	Height      int64                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Status      string                `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Components  []*ExecutionComponent `protobuf:"bytes,7,rep,name=components,proto3" json:"components,omitempty"`
}

func (m *Will) Reset()         { *m = Will{} }
func (m *Will) String() string { return proto.CompactTextString(m) }
func (*Will) ProtoMessage()    {}
func (*Will) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{6}
}

func (m *Will) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *Will) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Will.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *Will) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Will.Merge(m, src)
}

func (m *Will) XXX_Size() int {
	return m.Size()
}

func (m *Will) XXX_DiscardUnknown() {
	xxx_messageInfo_Will.DiscardUnknown(m)
}

var xxx_messageInfo_Will proto.InternalMessageInfo

// type to hold wills
type Wills struct {
	// the set of wills to return
	Wills []*Will `protobuf:"bytes,1,rep,name=wills,proto3" json:"wills,omitempty"`
}

func (m *Wills) Reset()         { *m = Wills{} }
func (m *Wills) String() string { return proto.CompactTextString(m) }
func (*Wills) ProtoMessage()    {}
func (*Wills) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{7}
}

func (m *Wills) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *Wills) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Wills.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *Wills) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wills.Merge(m, src)
}

func (m *Wills) XXX_Size() int {
	return m.Size()
}

func (m *Wills) XXX_DiscardUnknown() {
	xxx_messageInfo_Wills.DiscardUnknown(m)
}

var xxx_messageInfo_Wills proto.InternalMessageInfo

// WillIds represents a list of will IDs.
type WillIds struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (m *WillIds) Reset()         { *m = WillIds{} }
func (m *WillIds) String() string { return proto.CompactTextString(m) }
func (*WillIds) ProtoMessage()    {}
func (*WillIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_cec37ad7aa1ffe0b, []int{8}
}

func (m *WillIds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *WillIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WillIds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *WillIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WillIds.Merge(m, src)
}

func (m *WillIds) XXX_Size() int {
	return m.Size()
}

func (m *WillIds) XXX_DiscardUnknown() {
	xxx_messageInfo_WillIds.DiscardUnknown(m)
}

var xxx_messageInfo_WillIds proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ExecutionComponent)(nil), "cosmwasm.will.ExecutionComponent")
	proto.RegisterType((*TransferComponent)(nil), "cosmwasm.will.TransferComponent")
	proto.RegisterType((*ClaimComponent)(nil), "cosmwasm.will.ClaimComponent")
	proto.RegisterType((*SchnorrSignature)(nil), "cosmwasm.will.SchnorrSignature")
	proto.RegisterType((*PedersenCommitment)(nil), "cosmwasm.will.PedersenCommitment")
	proto.RegisterType((*GnarkZkSnark)(nil), "cosmwasm.will.GnarkZkSnark")
	proto.RegisterType((*Will)(nil), "cosmwasm.will.Will")
	proto.RegisterType((*Wills)(nil), "cosmwasm.will.Wills")
	proto.RegisterType((*WillIds)(nil), "cosmwasm.will.WillIds")
}

func init() { proto.RegisterFile("cosmwasm/will/types.proto", fileDescriptor_cec37ad7aa1ffe0b) }

var fileDescriptor_cec37ad7aa1ffe0b = []byte{
	// 833 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0x8e, 0x33, 0xf9, 0x99, 0x54, 0x32, 0x99, 0xd9, 0x66, 0xb5, 0xca, 0xfe, 0xd9, 0x83, 0x57,
	0xc0, 0xc2, 0xc1, 0xd1, 0xcc, 0xc2, 0x05, 0x04, 0x48, 0x0e, 0x3f, 0x33, 0x42, 0x42, 0xe0, 0x20,
	0x56, 0xda, 0x4b, 0xd4, 0xb1, 0x3b, 0x49, 0x6b, 0xe2, 0xee, 0xe0, 0x6e, 0xcf, 0x6e, 0xde, 0x82,
	0x0b, 0x12, 0x47, 0x8e, 0xbc, 0x01, 0xaf, 0xb0, 0xc7, 0x15, 0x27, 0xb8, 0x44, 0xe0, 0xb9, 0xf0,
	0x18, 0xa8, 0x7f, 0x9c, 0xf5, 0x64, 0xf6, 0x14, 0xd7, 0xf7, 0xd5, 0x57, 0xae, 0xfa, 0xe2, 0x2a,
	0xb8, 0x1b, 0x73, 0x91, 0x3e, 0xc7, 0x22, 0x1d, 0x3e, 0xa7, 0xcb, 0xe5, 0x50, 0xae, 0x57, 0x44,
	0x04, 0xab, 0x8c, 0x4b, 0x8e, 0x0e, 0x4a, 0x2a, 0x50, 0xd4, 0xbd, 0xdb, 0x73, 0x3e, 0xe7, 0x9a,
	0x19, 0xaa, 0x27, 0x93, 0x74, 0xcf, 0x55, 0x49, 0x5c, 0x0c, 0xa7, 0x58, 0x90, 0xe1, 0xe5, 0xc9,
	0x94, 0x48, 0x7c, 0x32, 0x8c, 0x39, 0x65, 0x86, 0xf7, 0xff, 0x76, 0x00, 0x7d, 0xf9, 0x82, 0xc4,
	0xb9, 0xa4, 0x9c, 0x8d, 0x78, 0xba, 0xe2, 0x8c, 0x30, 0x89, 0x10, 0x34, 0x18, 0x4e, 0xc9, 0xc0,
	0x39, 0x76, 0x1e, 0x77, 0x22, 0xfd, 0x8c, 0xfa, 0x50, 0xa7, 0xc9, 0xa0, 0xae, 0x91, 0x3a, 0x4d,
	0xd0, 0x1d, 0x68, 0x09, 0x89, 0x65, 0x2e, 0x06, 0x7b, 0x1a, 0xb3, 0x11, 0xfa, 0x0c, 0xf6, 0x65,
	0x86, 0x99, 0x98, 0x91, 0x6c, 0xd0, 0x38, 0x76, 0x1e, 0x77, 0x4f, 0x8f, 0x83, 0x6b, 0xad, 0x06,
	0x3f, 0x58, 0x7a, 0xfb, 0xbe, 0xb3, 0x5a, 0xb4, 0xd5, 0xa0, 0x8f, 0xa0, 0x19, 0x2f, 0x31, 0x4d,
	0x07, 0x4d, 0x2d, 0x7e, 0xb8, 0x23, 0x1e, 0x29, 0xae, 0xaa, 0x34, 0xd9, 0xe1, 0x11, 0xf4, 0xe3,
	0x12, 0x9d, 0x28, 0x9f, 0xfc, 0x1f, 0xe1, 0xd6, 0x8d, 0x37, 0xa9, 0x29, 0x24, 0xb7, 0x73, 0xd5,
	0x25, 0x47, 0x27, 0xd0, 0xc2, 0x29, 0xcf, 0x99, 0xd4, 0x53, 0x74, 0x4f, 0xef, 0x06, 0xc6, 0xb1,
	0x40, 0x39, 0x16, 0x58, 0xc7, 0x82, 0x11, 0xa7, 0x2c, 0xb2, 0x89, 0xfe, 0x9f, 0x0e, 0xf4, 0xaf,
	0x77, 0x81, 0x3e, 0x87, 0xfd, 0x15, 0x49, 0x48, 0x26, 0x08, 0xd3, 0x0e, 0x75, 0x4f, 0xdf, 0xde,
	0x69, 0xfb, 0x3b, 0x4b, 0x8f, 0x78, 0x9a, 0x52, 0x99, 0xda, 0xa1, 0x4b, 0x11, 0xfa, 0x04, 0xda,
	0x22, 0x5e, 0x30, 0x9e, 0x65, 0xb6, 0x0f, 0x6f, 0x47, 0x3f, 0x36, 0xec, 0x98, 0xce, 0x19, 0x96,
	0x79, 0x46, 0xce, 0x6a, 0x51, 0xa9, 0x40, 0x4f, 0xa0, 0x39, 0x67, 0x38, 0xbb, 0xb0, 0x76, 0xdf,
	0xdf, 0x91, 0x7e, 0xad, 0xb8, 0x67, 0x17, 0x63, 0xf5, 0xa3, 0xfc, 0xd2, 0xb9, 0xe1, 0x01, 0x74,
	0x45, 0xbc, 0x20, 0x29, 0x31, 0x66, 0xfd, 0xe2, 0xc0, 0xd1, 0xee, 0x3b, 0xd0, 0x43, 0x80, 0x55,
	0x3e, 0x5d, 0xd2, 0x78, 0x72, 0x41, 0xd6, 0xda, 0xb4, 0x5e, 0xd4, 0x31, 0xc8, 0x37, 0x64, 0x8d,
	0x3e, 0x80, 0x5b, 0x39, 0xa3, 0x3f, 0xe5, 0x64, 0x22, 0x88, 0x10, 0x94, 0xb3, 0x89, 0xfd, 0x40,
	0x7a, 0xd1, 0xa1, 0x21, 0xc6, 0x06, 0x3f, 0x4f, 0xd0, 0x03, 0xe8, 0x88, 0xb2, 0xae, 0x1e, 0xb1,
	0x17, 0xbd, 0x06, 0xd0, 0x00, 0xda, 0x29, 0x11, 0x02, 0xcf, 0x89, 0x9e, 0xa1, 0x13, 0x95, 0xa1,
	0xff, 0xab, 0x03, 0xe8, 0xa6, 0x77, 0xc8, 0x05, 0x88, 0xb7, 0x91, 0xed, 0xac, 0x82, 0xa0, 0x47,
	0x70, 0x90, 0x61, 0x96, 0xf0, 0x74, 0x32, 0xc3, 0xb1, 0xe4, 0x99, 0x6d, 0xab, 0x67, 0xc0, 0xaf,
	0x34, 0x86, 0x6e, 0x43, 0xf3, 0x12, 0x2f, 0xf3, 0xb2, 0x1f, 0x13, 0xa0, 0xf7, 0xe0, 0x70, 0xba,
	0xa4, 0x2c, 0xa1, 0x6c, 0x5e, 0x8a, 0x1b, 0x9a, 0xef, 0x97, 0xb0, 0x91, 0xfb, 0x12, 0x7a, 0x55,
	0x6b, 0xd1, 0xfb, 0x70, 0x74, 0x49, 0x32, 0x3a, 0xa3, 0x31, 0x56, 0xdb, 0x54, 0xf1, 0xec, 0xb0,
	0x8a, 0x2b, 0xe7, 0x1e, 0xc1, 0x81, 0x35, 0x96, 0xb2, 0x55, 0x2e, 0x45, 0xd9, 0x9e, 0x01, 0xcf,
	0x35, 0xa6, 0xda, 0x5b, 0x65, 0x9c, 0xcf, 0xca, 0xf6, 0x74, 0xe0, 0xff, 0x51, 0x87, 0xc6, 0x53,
	0xba, 0x5c, 0xa2, 0x3b, 0x7a, 0x1f, 0xf5, 0x97, 0x1c, 0xb6, 0x8a, 0x8d, 0x57, 0x3f, 0xff, 0x42,
	0xef, 0xe5, 0x3b, 0xd0, 0x8e, 0x33, 0x82, 0xcb, 0xa1, 0x3b, 0x61, 0xb7, 0xd8, 0x78, 0xed, 0x91,
	0x81, 0xa2, 0x92, 0x43, 0x0f, 0xec, 0x8a, 0xeb, 0xe5, 0x0d, 0xf7, 0x8b, 0x8d, 0xd7, 0xf8, 0x16,
	0xa7, 0xc4, 0x2e, 0xfb, 0x09, 0x74, 0xa7, 0x84, 0x91, 0x19, 0x8d, 0x29, 0xce, 0xd6, 0xe6, 0x4f,
	0x09, 0x0f, 0x8b, 0x8d, 0xd7, 0x0d, 0x5f, 0xc3, 0x51, 0x35, 0x07, 0xf9, 0xd0, 0x5a, 0x10, 0x3a,
	0x5f, 0x48, 0xbd, 0xb8, 0x7b, 0x21, 0x14, 0x1b, 0xaf, 0x75, 0xa6, 0x91, 0xc8, 0x32, 0x2a, 0xc7,
	0xde, 0x8c, 0x96, 0xae, 0xa8, 0x73, 0xc6, 0x1a, 0xd9, 0xde, 0x8f, 0xef, 0xf5, 0x5f, 0x6b, 0x16,
	0x4b, 0x0c, 0xda, 0xc7, 0x7b, 0x6f, 0xd8, 0xa6, 0x9b, 0x27, 0x2b, 0xec, 0x17, 0x1b, 0x0f, 0xb6,
	0xa1, 0x88, 0x2a, 0x45, 0x3e, 0x6e, 0xfc, 0xf7, 0x9b, 0xe7, 0xf8, 0x9f, 0x42, 0x53, 0x19, 0x27,
	0xd0, 0x87, 0xd0, 0x54, 0x55, 0xc4, 0xc0, 0xd1, 0xc5, 0xdf, 0xda, 0x29, 0xae, 0x92, 0xc2, 0x4e,
	0xb1, 0xf1, 0x4c, 0x7a, 0x64, 0x92, 0xfd, 0xfb, 0xd0, 0x56, 0xf1, 0x79, 0x22, 0xd0, 0x11, 0xec,
	0xd1, 0xc4, 0xc8, 0x3b, 0x91, 0x7a, 0x0c, 0xcf, 0x5e, 0xfe, 0xeb, 0xd6, 0x7e, 0x2f, 0x5c, 0xe7,
	0x65, 0xe1, 0x3a, 0xaf, 0x0a, 0xd7, 0xf9, 0xa7, 0x70, 0x9d, 0x9f, 0xaf, 0xdc, 0xda, 0xab, 0x2b,
	0xb7, 0xf6, 0xd7, 0x95, 0x5b, 0x7b, 0xf6, 0xee, 0x9c, 0xca, 0x45, 0x3e, 0x0d, 0x62, 0x9e, 0x0e,
	0x47, 0x5c, 0xa4, 0x4f, 0xf5, 0x51, 0xc7, 0x22, 0x4d, 0x86, 0x2f, 0x2a, 0xc7, 0x7d, 0xda, 0xd2,
	0x87, 0xf9, 0xc9, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x33, 0x51, 0x95, 0xaa, 0xfa, 0x05, 0x00,
	0x00,
}

func (this *ExecutionComponent) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExecutionComponent)
	if !ok {
		that2, ok := that.(ExecutionComponent)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if that1.ComponentType == nil {
		if this.ComponentType != nil {
			return false
		}
	} else if this.ComponentType == nil {
		return false
	} else if !this.ComponentType.Equal(that1.ComponentType) {
		return false
	}
	return true
}

func (this *ExecutionComponent_Transfer) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExecutionComponent_Transfer)
	if !ok {
		that2, ok := that.(ExecutionComponent_Transfer)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Transfer.Equal(that1.Transfer) {
		return false
	}
	return true
}

func (this *ExecutionComponent_Claim) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExecutionComponent_Claim)
	if !ok {
		that2, ok := that.(ExecutionComponent_Claim)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Claim.Equal(that1.Claim) {
		return false
	}
	return true
}

func (this *TransferComponent) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TransferComponent)
	if !ok {
		that2, ok := that.(TransferComponent)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.To != that1.To {
		return false
	}
	if !this.Amount.Equal(that1.Amount) {
		return false
	}
	return true
}

func (this *ClaimComponent) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ClaimComponent)
	if !ok {
		that2, ok := that.(ClaimComponent)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.SchemeType == nil {
		if this.SchemeType != nil {
			return false
		}
	} else if this.SchemeType == nil {
		return false
	} else if !this.SchemeType.Equal(that1.SchemeType) {
		return false
	}
	return true
}

func (this *ClaimComponent_Pedersen) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ClaimComponent_Pedersen)
	if !ok {
		that2, ok := that.(ClaimComponent_Pedersen)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Pedersen.Equal(that1.Pedersen) {
		return false
	}
	return true
}

func (this *ClaimComponent_Schnorr) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ClaimComponent_Schnorr)
	if !ok {
		that2, ok := that.(ClaimComponent_Schnorr)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Schnorr.Equal(that1.Schnorr) {
		return false
	}
	return true
}

func (this *ClaimComponent_Gnark) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ClaimComponent_Gnark)
	if !ok {
		that2, ok := that.(ClaimComponent_Gnark)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Gnark.Equal(that1.Gnark) {
		return false
	}
	return true
}

func (this *SchnorrSignature) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SchnorrSignature)
	if !ok {
		that2, ok := that.(SchnorrSignature)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.PublicKey, that1.PublicKey) {
		return false
	}
	if !bytes.Equal(this.UniqueSessionId, that1.UniqueSessionId) {
		return false
	}
	if !bytes.Equal(this.Signature, that1.Signature) {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	return true
}

func (this *PedersenCommitment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PedersenCommitment)
	if !ok {
		that2, ok := that.(PedersenCommitment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Commitment, that1.Commitment) {
		return false
	}
	if !bytes.Equal(this.RandomFactor, that1.RandomFactor) {
		return false
	}
	if !bytes.Equal(this.Value, that1.Value) {
		return false
	}
	if !bytes.Equal(this.BlindingFactor, that1.BlindingFactor) {
		return false
	}
	return true
}

func (this *GnarkZkSnark) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GnarkZkSnark)
	if !ok {
		that2, ok := that.(GnarkZkSnark)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.VerificationKey, that1.VerificationKey) {
		return false
	}
	if !bytes.Equal(this.PublicInputs, that1.PublicInputs) {
		return false
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return false
	}
	return true
}

func (this *Will) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Will)
	if !ok {
		that2, ok := that.(Will)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.Creator != that1.Creator {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Beneficiary != that1.Beneficiary {
		return false
	}
	if this.Height != that1.Height {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if len(this.Components) != len(that1.Components) {
		return false
	}
	for i := range this.Components {
		if !this.Components[i].Equal(that1.Components[i]) {
			return false
		}
	}
	return true
}

func (this *Wills) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Wills)
	if !ok {
		that2, ok := that.(Wills)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Wills) != len(that1.Wills) {
		return false
	}
	for i := range this.Wills {
		if !this.Wills[i].Equal(that1.Wills[i]) {
			return false
		}
	}
	return true
}

func (this *WillIds) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WillIds)
	if !ok {
		that2, ok := that.(WillIds)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Ids) != len(that1.Ids) {
		return false
	}
	for i := range this.Ids {
		if this.Ids[i] != that1.Ids[i] {
			return false
		}
	}
	return true
}

func (m *ExecutionComponent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionComponent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionComponent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ComponentType != nil {
		{
			size := m.ComponentType.Size()
			i -= size
			if _, err := m.ComponentType.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ExecutionComponent_Transfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionComponent_Transfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Transfer != nil {
		{
			size, err := m.Transfer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}

func (m *ExecutionComponent_Claim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionComponent_Claim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Claim != nil {
		{
			size, err := m.Claim.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}

func (m *TransferComponent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransferComponent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransferComponent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClaimComponent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClaimComponent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClaimComponent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SchemeType != nil {
		{
			size := m.SchemeType.Size()
			i -= size
			if _, err := m.SchemeType.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *ClaimComponent_Pedersen) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClaimComponent_Pedersen) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Pedersen != nil {
		{
			size, err := m.Pedersen.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *ClaimComponent_Schnorr) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClaimComponent_Schnorr) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Schnorr != nil {
		{
			size, err := m.Schnorr.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}

func (m *ClaimComponent_Gnark) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClaimComponent_Gnark) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Gnark != nil {
		{
			size, err := m.Gnark.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}

func (m *SchnorrSignature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SchnorrSignature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SchnorrSignature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.UniqueSessionId) > 0 {
		i -= len(m.UniqueSessionId)
		copy(dAtA[i:], m.UniqueSessionId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.UniqueSessionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PedersenCommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PedersenCommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PedersenCommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BlindingFactor) > 0 {
		i -= len(m.BlindingFactor)
		copy(dAtA[i:], m.BlindingFactor)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BlindingFactor)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RandomFactor) > 0 {
		i -= len(m.RandomFactor)
		copy(dAtA[i:], m.RandomFactor)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RandomFactor)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GnarkZkSnark) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GnarkZkSnark) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GnarkZkSnark) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PublicInputs) > 0 {
		i -= len(m.PublicInputs)
		copy(dAtA[i:], m.PublicInputs)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PublicInputs)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VerificationKey) > 0 {
		i -= len(m.VerificationKey)
		copy(dAtA[i:], m.VerificationKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VerificationKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Will) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Will) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Will) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Components) > 0 {
		for iNdEx := len(m.Components) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Components[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Wills) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Wills) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Wills) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Wills) > 0 {
		for iNdEx := len(m.Wills) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Wills[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *WillIds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WillIds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WillIds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for iNdEx := len(m.Ids) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Ids[iNdEx])
			copy(dAtA[i:], m.Ids[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Ids[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *ExecutionComponent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ComponentType != nil {
		n += m.ComponentType.Size()
	}
	return n
}

func (m *ExecutionComponent_Transfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Transfer != nil {
		l = m.Transfer.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ExecutionComponent_Claim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Claim != nil {
		l = m.Claim.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *TransferComponent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ClaimComponent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SchemeType != nil {
		n += m.SchemeType.Size()
	}
	return n
}

func (m *ClaimComponent_Pedersen) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pedersen != nil {
		l = m.Pedersen.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ClaimComponent_Schnorr) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Schnorr != nil {
		l = m.Schnorr.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ClaimComponent_Gnark) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Gnark != nil {
		l = m.Gnark.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *SchnorrSignature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.UniqueSessionId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *PedersenCommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.RandomFactor)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BlindingFactor)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *GnarkZkSnark) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VerificationKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.PublicInputs)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Will) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Components) > 0 {
		for _, e := range m.Components {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *Wills) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Wills) > 0 {
		for _, e := range m.Wills {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *WillIds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *ExecutionComponent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionComponent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionComponent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transfer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TransferComponent{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ComponentType = &ExecutionComponent_Transfer{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ClaimComponent{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ComponentType = &ExecutionComponent_Claim{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *TransferComponent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransferComponent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransferComponent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.Coin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *ClaimComponent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClaimComponent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClaimComponent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pedersen", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &PedersenCommitment{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.SchemeType = &ClaimComponent_Pedersen{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Schnorr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &SchnorrSignature{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.SchemeType = &ClaimComponent_Schnorr{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gnark", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &GnarkZkSnark{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.SchemeType = &ClaimComponent_Gnark{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *SchnorrSignature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SchnorrSignature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SchnorrSignature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueSessionId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniqueSessionId = append(m.UniqueSessionId[:0], dAtA[iNdEx:postIndex]...)
			if m.UniqueSessionId == nil {
				m.UniqueSessionId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *PedersenCommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PedersenCommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PedersenCommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomFactor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RandomFactor = append(m.RandomFactor[:0], dAtA[iNdEx:postIndex]...)
			if m.RandomFactor == nil {
				m.RandomFactor = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlindingFactor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlindingFactor = append(m.BlindingFactor[:0], dAtA[iNdEx:postIndex]...)
			if m.BlindingFactor == nil {
				m.BlindingFactor = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *GnarkZkSnark) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GnarkZkSnark: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GnarkZkSnark: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationKey = append(m.VerificationKey[:0], dAtA[iNdEx:postIndex]...)
			if m.VerificationKey == nil {
				m.VerificationKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicInputs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicInputs = append(m.PublicInputs[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicInputs == nil {
				m.PublicInputs = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Will) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Will: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Will: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Components", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Components = append(m.Components, &ExecutionComponent{})
			if err := m.Components[len(m.Components)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Wills) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Wills: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Wills: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wills", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wills = append(m.Wills, &Will{})
			if err := m.Wills[len(m.Wills)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *WillIds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WillIds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WillIds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ids", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ids = append(m.Ids, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
