name: Rugsafe Protocol

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build Protocol
      run: make build

    - name: Kill Tmux Session and Processes
      run: |
        tmux send-keys -t rugsafe-protocol C-c || true
        sleep 5  # Give some time for the processes to terminate gracefully
        tmux kill-session -t rugsafe-protocol || true
        fuser -k 26657/tcp || true  # Force kill any process still using the port

    - name: Run protocol
      run: |
        tmux new -d -s rugsafe-protocol 'sh -c "CHAINNAME=rugsafe-testnet make run"'
