name: Willchain Protocol

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build Protocol
      run: make build

    - name: Kill Tmux Session
      run: tmux kill-session -t willchain-protocol || true

    - name: Run Explorer
      run: tmux new -d -s willchain-protocol 'sh -c "make run"';